name: clubhouse
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  agora_rtc_engine: ^4.2.0
  permission_handler: ^8.3.0
  firebase_auth:
  firebase_core: ^0.4.4
  cloud_firestore: ^0.12.9
  country_code_picker: ^2.0.2
  pull_to_refresh: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
